pydep/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, CourseViewSet, ModuleViewSet, LessonViewSet

app_name = "api"

router_1 = DefaultRouter()
router_1.register("users", UserViewSet)
router_1.register("courses", CourseViewSet)
router_1.register("modules", ModuleViewSet)
router_1.register("lessons", LessonViewSet)

urlpatterns = [
    path('', include(router_1.urls)),
]

pydep/course_editor/urls.py
from django.urls import path

from .views import lesson_create
from .views import lesson_edit
from .views import upload_image
from .views import course_editor_main
from .views import course_create
from .views import module_create
from .views import my_courses
from .views import course_edit
from .views import module_edit

app_name = 'studio'

urlpatterns = [
    path(
        "",
        course_editor_main,
        name="main"
    ),
    path(
        "course/create/",
        course_create,
        name="course_create"
    ),
    path(
        "course/<int:course_id>/edit/",
        course_edit,
        name="course_edit"
    ),
    path(
        'course/<int:course_id>/module/create/',
        module_create,
        name='module_create'
    ),
    path(
        'course/<int:course_id>/module/<int:module_id>/edit/',
        module_edit,
        name='module_edit'
    ),
    path(
        'course/<int:course_id>/module/<int:module_id>/lesson/create/',
        lesson_create,
        name='lesson_create'
    ),
    path(
        'course/<int:course_id>/module/<int:module_id>/lesson/<int:lesson_id>/edit/',
        lesson_edit,
        name='lesson_edit'
    ),
    path(
        'upload-image/',
        upload_image,
        name='upload_image'
    ),
    path(
        "my_courses/",
        my_courses,
        name="my_courses"
    ),
]

pydep/lesson/urls.py
from django.urls import path

from .views import course_detail
from .views import courses_list
from .views import index
from .views import lesson_detail
from .views import profile
from .views import module_detail
from .views import profile_edit
from .views import category_detail
from .views import complete_lesson
# from .views import lesson_edit
# from .views import lesson_create
# from .views import upload_image
from .views import course_editor

app_name = 'lesson'

urlpatterns = [
    path(
        '',
        index,
        name='index'
    ),
    path(
        'profile/',
        profile,
        name='profile'
    ),
    path(
        'profile/edit/',
        profile_edit,
        name='profile_edit'
    ),
    path(
        'courses/',
        courses_list,
        name='courses'
    ),
    path(
        'course/<str:course_name>/',
        course_detail,
        name='course_detail'
    ),
    path(
        "courses/<str:slug>",
        category_detail,
        name="category"
    ),
    path(
        'course/<str:course_name>/<str:module_name>/',
        module_detail,
        name='module_detail'),
    path(
        'course/<str:course_name>/<str:module_name>/<str:lesson_name>/',
        lesson_detail,
        name='lesson_detail'
    ),
    path(
        '<str:course_name>/<str:module_name>/<str:lesson_name>/complete/',
        complete_lesson,
        name='complete_lesson'
    ),
    # path(
    #     'lesson/create/',
    #     lesson_create,
    #     name='lesson_create'
    # ),
    # path(
    #     'lesson/<int:lesson_id>/edit/',
    #     lesson_edit,
    #     name='lesson_edit'
    # ),
    # path(
    #     'upload-image/',
    #     upload_image,
    #     name='upload_image'
    # ),
]

pydep/pydep/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lesson.urls', namespace='lesson')),
    path("studio/", include("course_editor.urls", namespace="studio")),
    path('', include('users.urls', namespace='users')),
    path('tutor/', include('tutor.urls', namespace='tutor')),
    path("api/", include("api.urls", namespace="api")),
]

urlpatterns += [
    path(
        "ckeditor5/",
        include('django_ckeditor_5.urls'),
        name="ck_editor_5_upload_file"
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pydep/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import SignUp
from .views import SignIn

app_name = 'users'

urlpatterns = [
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signin/', SignIn, name='signin'),
    path('signup/', SignUp.as_view(
        template_name='users/signup.html'
    ), name='signup')
]

pydep/lesson/models.py
from django_ckeditor_5.fields import CKEditor5Field
from django.db import models
from django.utils.text import slugify
from transliterate import translit
import json


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Название'
    )
    slug = models.SlugField(
        unique=True,
        blank=True
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def save(self, *args, **kwargs):
        if not self.slug:
            # Транслитерируем с русского → английский, затем слаг
            transliterated = translit(self.name, 'ru', reversed=True)
            self.slug = slugify(transliterated)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    description = CKEditor5Field('Text', config_name='extends', blank=True, null=True)
    # Блочный контент урока - массив блоков в формате Editor.js
    content_blocks = models.JSONField(
        default=list,
        blank=True,
        verbose_name='Блоки контента',
        help_text='Структурированный контент урока в формате блоков'
    )
    authors = models.ManyToManyField(
        "users.CustomUser",
        related_name="authored_lessons",
        verbose_name="Авторы"
    )

    class Meta:
        verbose_name = 'Урок'
        verbose_name_plural = 'Уроки'

    def __str__(self):
        return self.title

    def has_blocks(self):
        """Проверяет, есть ли блоки контента"""
        return bool(self.content_blocks and len(self.content_blocks) > 0)


class Module(models.Model):
    title = models.CharField(
        max_length=255,
        unique=True,
        verbose_name="Название"
    )
    description = models.TextField(
        verbose_name='Описание'
    )
    image = models.ImageField(
        upload_to='courses/modules',
        verbose_name='Логотип модуля'
    )
    lessons = models.ManyToManyField(
        Lesson,
        through="LessonsInModule",
        verbose_name="Уроки"
    )
    authors = models.ManyToManyField(
        "users.CustomUser",
        related_name="authored_modules",
        verbose_name="Авторы"
    )

    class Meta:
        verbose_name = 'Модуль'
        verbose_name_plural = 'Модули'

    def __str__(self):
        return self.title


class Course(models.Model):
    level_choices = [
        ("С нуля", "С нуля"),
        ("С опытом", "С опытом")
    ]
    category_choices = [
        ("Программирование", "Программирование")
    ]
    name = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Название'
    )
    description = models.TextField(
        verbose_name='Описание'
    )
    price = models.IntegerField(
        default=1000,
        verbose_name='Цена'
    )
    image = models.ImageField(
        upload_to='courses',
        verbose_name='Логотип курса'
    )
    duration = models.IntegerField(
        default=3,
        verbose_name="Продолжительность"
    )
    level = models.CharField(
        choices=level_choices,
        max_length=50,
        default="С нуля",
        verbose_name="Уровень"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="Категория",
        null=True
    )
    modules = models.ManyToManyField(
        Module,
        through='ModulesInCourse',
        verbose_name='Модули'
    )
    programming_language = models.CharField(max_length=255)
    authors = models.ManyToManyField(
        "users.CustomUser",
        related_name="authored_courses",
        verbose_name="Авторы"
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name="Опубликован"
    )

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

    # def save(self, *args, **kwargs):
    #     if not self.slug:
    #         # Транслитерируем с русского → английский, затем слаг
    #         transliterated = translit(self.name, 'ru', reversed=True)
    #         self.slug = slugify(transliterated)
    #     super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class ModulesInCourse(models.Model):
    module = models.ForeignKey(
        Module,
        on_delete=models.CASCADE,
        verbose_name='Модуль'
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        verbose_name='Курс'
    )
    sequence_number = models.IntegerField(
        default=1,
        verbose_name="Порядковый номер модуля"
    )

    class Meta:
        verbose_name = 'Модули в курсе'
        verbose_name_plural = 'Модули в курсах'


class LessonsInModule(models.Model):
    module = models.ForeignKey(
        Module,
        on_delete=models.CASCADE,
        verbose_name='Модуль'
    )
    lesson = models.ForeignKey(
        Lesson,
        on_delete=models.CASCADE,
        verbose_name='Урок'
    )
    sequence_number = models.IntegerField(
        default=1,
        verbose_name="Порядковый номер урока"
    )

    class Meta:
        verbose_name = 'Уроки в модуле'
        verbose_name_plural = 'Уроки в модулях'


class UserLessonProgress(models.Model):
    user = models.ForeignKey(
        "users.CustomUser",
        on_delete=models.CASCADE,
        related_name="lesson_progress"
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        related_name="lesson_progress"
    )
    module = models.ForeignKey(
        Module,
        on_delete=models.CASCADE,
        related_name="lesson_progress"
    )
    lesson = models.ForeignKey(
        Lesson,
        on_delete=models.CASCADE,
        related_name="lesson_progress"
    )
    completed = models.BooleanField(default=False)
    current = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Прогресс прохождения урока"
        verbose_name_plural = "Прогресс прохождения уроков"

    def __str__(self):
        return f"{self.user} {self.lesson} {self.completed}"


class Cohort(models.Model):
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        related_name="cohorts",
        verbose_name="Когорта"
    )
    students = models.ManyToManyField(
        "users.CustomUser",
        verbose_name="Студенты"
    )
    start_date = models.DateField(
        verbose_name="Дата старта"
    )

    class Meta:
        verbose_name = "Когорта"
        verbose_name_plural = "Когорты"

    def __str__(self):
        return f"№{self.id} - {self.course.name} ({self.start_date})"


class CourseEnrollment(models.Model):
    user = models.ForeignKey(
        "users.CustomUser",
        on_delete=models.CASCADE,
        related_name="course_learn",
        verbose_name="Пользователь"
    )
    course = models.ForeignKey(
        Course,
        on_delete=models.CASCADE,
        verbose_name="Курс"
    )
    enrolled_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Куплен"
    )

    class Meta:
        verbose_name = "Запись на курс"
        verbose_name_plural = "Записи на курсы"

    def __str__(self):
        return f"{self.user} - {self.course}"

pydep/lesson/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model

from .models import Lesson


# class RegisterCourseForm(ModelForm):
#     date_choices = [
#         ('2022-01-01', '1 января 2022'),
#         ('2022-02-01', '1 февраля 2022'),
#         ('2022-03-01', '1 марта 2022'),
#     ]
#     start_date = forms.ChoiceField(choices=date_choices)
#
#     class Meta:
#         model = RegisterCourse
#         fields = ['start_date',]
#         labels = {
#             'start_date': _('Дата старта потока')
#         }


class EditProfile(UserChangeForm):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control form-container',
                'placeholder': 'Введите ваш email',
                'type': "email",
                'id': "floatingInput"
            }
        ),
        label='Почта',
        required=False
    )
    image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control form-container',
                'placeholder': 'Выберите изображение',
                'id': "floatingInput"
            }
        ),
        label='Фотография',
        required=False
    )
    description = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control form-container',
                'placeholder': 'Выберите изображение',
                'id': "floatingInput"
            }
        ),
        label='Статус',
        required=False
    )
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control form-container',
                'placeholder': 'Выберите изображение',
                'id': "floatingInput"
            }
        ),
        label='Имя',
        required=False
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control form-container',
                'placeholder': 'Выберите изображение',
                'id': "floatingInput"
            }
        ),
        label='Фамилия',
        required=False
    )

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'image', 'first_name', 'last_name', 'description')


# class CreateLessonForm(forms.ModelForm):
#     content_blocks_json = forms.CharField(
#         widget=forms.HiddenInput(),
#         required=False,
#         label=''
#     )
#
#     class Meta:
#         model = Lesson
#         fields = ("title", "description", "content_blocks")
#         widgets = {
#             'description': CKEditor5Widget(config_name='extends'),
#             'content_blocks': forms.HiddenInput(),
#         }
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         # Временно убираем обязательность поля
#         self.fields['description'].required = False
#         self.fields['content_blocks'].required = False
#
#         # Если есть экземпляр, преобразуем content_blocks в JSON строку
#         if self.instance and self.instance.pk and self.instance.content_blocks:
#             import json
#             try:
#                 self.fields['content_blocks_json'].initial = json.dumps(self.instance.content_blocks, ensure_ascii=False)
#             except (TypeError, ValueError):
#                 self.fields['content_blocks_json'].initial = '[]'
#
#     def clean(self):
#         cleaned_data = super().clean()
#         content_blocks_json = cleaned_data.get('content_blocks_json')
#
#         if content_blocks_json:
#             import json
#             try:
#                 blocks = json.loads(content_blocks_json)
#                 cleaned_data['content_blocks'] = blocks
#             except json.JSONDecodeError:
#                 raise forms.ValidationError('Неверный формат JSON для блоков контента')
#
#         return cleaned_data

pydep/templates/lesson/courses_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block title %}
    Курсы
{% endblock %}

{% block static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .course-card {
            border-radius: 15px;
            overflow: hidden;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
            margin-bottom: 20px;
            background-color: #ffffff;
            opacity: 0;
            transform: translateY(20px);
            animation: fadeInUp 0.6s ease forwards;
            display: flex;
            flex-direction: column;
            height: 100%;
        }

        .course-card[data-delay] {
            animation-delay: calc(var(--delay-index) * 0.1s);
        }

        .course-card:hover {
            transform: translateY(-10px);
            box-shadow: 0 8px 16px rgba(0, 0, 0, 0.15);
        }

        .course-content {
            padding: 20px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            height: 100%;
        }

        .course-title {
            font-size: 1.25rem;
            font-weight: bold;
            min-height: 3.6em;
            line-height: 1.2;
        }

        .course-meta {
            font-size: 0.75rem;
            color: #6c757d;
            margin-bottom: 8px;
        }

        .course-image-wrapper {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 140px;
            margin-bottom: 20px;
        }

        .course-image-wrapper img {
            max-height: 100%;
            max-width: 100%;
            object-fit: contain;
        }

        .btn-course-detail {
            border-radius: 15px;
            margin-top: auto;
        }

        .empty-message {
            max-width: 600px;
            margin: 80px auto;
            padding: 40px;
            text-align: center;
            background: linear-gradient(135deg, #f8f9fa, #e9ecef);
            border-radius: 20px;
            box-shadow: 0 2px 20px rgba(0, 0, 0, 0.05);
            font-size: 1.3rem;
            color: #495057;
            animation: fadeInUp 0.8s ease both;
        }

        .row.gy-4 > [class*='col-'] {
            margin-bottom: 1.5rem;
        }

        .filters-section {
            background: linear-gradient(135deg, #f8f9fa 0%, #ffffff 100%);
            border-radius: 20px;
            padding: 30px;
            margin-bottom: 40px;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.08);
        }

        .category-filters {
            display: flex;
            flex-wrap: wrap;
            gap: 12px;
            margin-bottom: 25px;
        }

        .category-filter-item {
            position: relative;
        }

        .category-filter-item input[type="checkbox"] {
            position: absolute;
            opacity: 0;
            cursor: pointer;
            height: 0;
            width: 0;
        }

        .category-filter-label {
            display: inline-block;
            padding: 12px 24px;
            font-size: 0.95rem;
            font-weight: 500;
            color: #495057;
            background: #ffffff;
            border: 2px solid #e9ecef;
            border-radius: 50px;
            cursor: pointer;
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            user-select: none;
            white-space: nowrap;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
        }

        .category-filter-label:hover {
            border-color: #6c757d;
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        }

        .category-filter-item input[type="checkbox"]:checked + .category-filter-label {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #ffffff;
            border-color: transparent;
            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
            transform: translateY(-2px);
        }

        .category-filter-item input[type="checkbox"]:checked + .category-filter-label:hover {
            box-shadow: 0 6px 20px rgba(102, 126, 234, 0.5);
            transform: translateY(-3px);
        }

        .reset-filters-btn {
            padding: 12px 24px;
            font-size: 0.95rem;
            font-weight: 500;
            color: #6c757d;
            background: #ffffff;
            border: 2px solid #e9ecef;
            border-radius: 50px;
            text-decoration: none;
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            display: inline-flex;
            align-items: center;
            gap: 8px;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
        }

        .reset-filters-btn:hover {
            background: #f8f9fa;
            border-color: #dee2e6;
            color: #495057;
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
        }

        .search-wrapper {
            position: relative;
            margin-bottom: 0;
        }

        .search-input {
            padding: 16px 20px;
            padding-left: 50px;
            font-size: 1rem;
            border: 2px solid #e9ecef;
            border-radius: 50px;
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            background: #ffffff;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.05);
        }

        .search-input:focus {
            outline: none;
            border-color: #667eea;
            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.2);
            transform: translateY(-2px);
        }

        .search-icon {
            position: absolute;
            left: 18px;
            top: 50%;
            transform: translateY(-50%);
            color: #6c757d;
            font-size: 1.1rem;
            pointer-events: none;
        }

        .search-btn {
            position: absolute;
            right: 8px;
            top: 50%;
            transform: translateY(-50%);
            padding: 10px 24px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border: none;
            border-radius: 50px;
            color: #ffffff;
            font-weight: 500;
            font-size: 0.95rem;
            cursor: pointer;
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            box-shadow: 0 2px 10px rgba(102, 126, 234, 0.3);
        }

        .search-btn:hover {
            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
            transform: translateY(-50%) translateY(-2px);
        }

        .search-btn:active {
            transform: translateY(-50%) translateY(0);
        }

        .filters-title {
            font-size: 1.3rem;
            font-weight: 600;
            color: #212529;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .filters-title::before {

            font-size: 1.2rem;
        }

        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(20px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container py-4">

            {#        {% if categories %}#}
            {#        <div class="category-filters">#}
            {#            {% for cat in categories %}#}
            {#                <a href="{% url "lesson:category" cat.slug %}" class="{% if cat == category %}active{% endif %}">{{ cat.name }}</a>#}
            {#            {% endfor %}#}
            {#            <a href="{% url "lesson:courses" %}" class="btn btn-light">Сбросить фильтры</a>#}
            {#        </div>#}
            {#        {% endif %}#}

            <form method="POST">
                {% csrf_token %}
                <div class="filters-section">
                    <div class="filters-title">Фильтры и поиск</div>

                    {% if categories %}
                        <div class="category-filters">
                            {% for cat in categories %}
                                {% if cat.slug in selected_category_slugs %}
                                    <div class="category-filter-item">
                                        <input type="checkbox" id="cat_{{ cat.slug }}" name="category"
                                               value="{{ cat.slug }}" checked>
                                        <label for="cat_{{ cat.slug }}" class="category-filter-label">{{ cat.name }}</label>
                                    </div>
                                {% else %}
                                    <div class="category-filter-item">
                                        <input type="checkbox" id="cat_{{ cat.slug }}" name="category"
                                               value="{{ cat.slug }}">
                                        <label for="cat_{{ cat.slug }}" class="category-filter-label">{{ cat.name }}</label>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <a href="{% url "lesson:courses" %}" class="reset-filters-btn">
                                <span>↻</span>
                                <span>Сбросить</span>
                            </a>
                        </div>
                    {% endif %}

                    <div class="search-wrapper">
                        <span class="search-icon">🔍</span>
                        <input type="search" name="q" class="form-control search-input" 
                               placeholder="Поиск по названию курса..." 
                               aria-label="Search"
                               value="{{ request.GET.q|default:'' }}">
                        <button type="submit" class="search-btn">Найти</button>
                    </div>
                </div>
            </form>

            <div class="row gy-4">
                {% for course in courses %}
                    <div class="col-md-6 col-lg-4 col-xl-3 d-flex">
                        <div class="course-card w-100" data-delay style="--delay-index: {{ forloop.counter0 }};">
                            <div class="course-content">
                                <div class="course-meta">
                                    {{ course.category }} · {{ course.duration|pluralize_months }} · {{ course.level }}
                                </div>
                                <div class="course-title mb-3">{{ course.name }}</div>
                                <div class="course-image-wrapper">
                                    <img src="{{ course.image.url }}" alt="{{ course.name }}">
                                </div>
                                <div>
                                    <div class="fw-bold mb-1">от {{ course.monthly_price }} ₽/мес</div>
                                    <div class="text-muted small">или сразу {{ course.price }} ₽</div>
                                </div>
                                <a href="{% url 'lesson:course_detail' course.name %}"
                                   class="btn btn-outline-primary btn-course-detail">Подробнее</a>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <div class="empty-message">
                        <p class="mb-0">Пока что курсы не добавлены.<br>Пожалуйста, загляните позже или свяжитесь с
                            администратором.</p>
                    </div>
                {% endfor %}
    {% include 'lesson/includes/paginator.html' %}
            </div>
        </div>
    </div>
{% endblock %}

pydep/templates/lesson/courses_list_about_languages.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    Курсы
{% endblock %}

{% block content %}
    <div class="container py-5">
        {% for course in courses %}
            <div class="card mb-3" style="max-width: 540px;">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <a href={% url "lesson:course_detail" course.name %}>
                    <img src={{ course.image.url }} %} class="card-img" alt="...">
                        </a>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ course.name }}</h5>
                        <p class="card-text">{{ course.description }}</p>
                        <p class="card-text"><small class="text-muted">{{ course.price }} руб.</small></p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
{% endblock %}

pydep/templates/lesson/create_lesson.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Создание урока{% endblock %}
{% block static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container py-5 d-flex justify-content-center">
    <div class="w-100" style="max-width: 720px;">
        {{ form.media }}
        <h2 class="mb-4 fw-bold text-primary" style="font-size: 2rem;">Создание урока</h2>
        <form method="POST" enctype="multipart/form-data" class="bg-white p-4 shadow rounded-4">
            {% csrf_token %}

            <div class="mb-3">
                <label for="{{ form.title.id_for_label }}" class="form-label fw-semibold">Название урока</label>
                {{ form.title|add_class:"form-control form-control-lg" }}
            </div>

            <div class="mb-4">
                <label for="{{ form.description.id_for_label }}" class="form-label fw-semibold">Описание</label>
                {{ form.description|safe }}
            </div>
    <input type="submit">
{#            <button type="submit" class="btn btn-primary btn-lg">Создать</button>#}
        </form>
    </div>
</div>
{% endblock %}

pydep/templates/lesson/permission_denied.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>В доступе отказано</title>
</head>
<body>
В доступе отказано
</body>
</html>

pydep/templates/lesson/projects.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Онлайн обучение — будущее за тобой{% endblock %}

{% block static %}

{% endblock %}

{% block content %}
{{ html_code|safe }}
{% endblock %}

pydep/templates/lesson/projects_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Онлайн обучение — будущее за тобой{% endblock %}

{% block static %}

{% endblock %}

{% block content %}
{{ html_code|safe }}
{% endblock %}