pydep/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from .views import UserViewSet, CourseViewSet, ModuleViewSet, LessonViewSet

app_name = "api"

router_1 = DefaultRouter()
router_1.register("users", UserViewSet)
router_1.register("courses", CourseViewSet)
router_1.register("modules", ModuleViewSet)
router_1.register("lessons", LessonViewSet)

urlpatterns = [
    path('', include(router_1.urls)),
]

pydep/lesson/urls.py
from django.urls import path

from .views import course_detail
from .views import courses_list
from .views import index
from .views import lesson_detail
from .views import profile
from .views import module_detail
from .views import profile_edit
from .views import category_detail
from .views import complete_lesson
# from .views import lesson_edit
# from .views import lesson_create
# from .views import upload_image
from .views import course_editor

app_name = 'lesson'

urlpatterns = [
    path(
        '',
        index,
        name='index'
    ),
    path(
        'profile/',
        profile,
        name='profile'
    ),
    path(
        'profile/edit/',
        profile_edit,
        name='profile_edit'
    ),
    path(
        'courses/',
        courses_list,
        name='courses'
    ),
    path(
        'course/<str:course_name>/',
        course_detail,
        name='course_detail'
    ),
    path(
        "courses/<str:slug>",
        category_detail,
        name="category"
    ),
    path(
        'course/<str:course_name>/<str:module_name>/',
        module_detail,
        name='module_detail'),
    path(
        'course/<str:course_name>/<str:module_name>/<str:lesson_name>/',
        lesson_detail,
        name='lesson_detail'
    ),
    path(
        '<str:course_name>/<str:module_name>/<str:lesson_name>/complete/',
        complete_lesson,
        name='complete_lesson'
    ),
    # path(
    #     'lesson/create/',
    #     lesson_create,
    #     name='lesson_create'
    # ),
    # path(
    #     'lesson/<int:lesson_id>/edit/',
    #     lesson_edit,
    #     name='lesson_edit'
    # ),
    # path(
    #     'upload-image/',
    #     upload_image,
    #     name='upload_image'
    # ),
]

pydep/pydep/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lesson.urls', namespace='lesson')),
    path("studio/", include("course_editor.urls", namespace="studio")),
    path('', include('users.urls', namespace='users')),
    path('tutor/', include('tutor.urls', namespace='tutor')),
    path("api/", include("api.urls", namespace="api")),
]

urlpatterns += [
    path(
        "ckeditor5/",
        include('django_ckeditor_5.urls'),
        name="ck_editor_5_upload_file"
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pydep/tutor/urls.py
from django.urls import path

from .views import my_tutor
from .views import projectbox
from .views import profile
from .views import schedule
from .views import lesson_create, lesson_update, lesson_payment_toggle

app_name = 'tutor'

urlpatterns = [
    path('', my_tutor, name='my_tutor'),
    path('projectbox/', projectbox, name='projectbox'),
    path('profile/', profile, name='profile'),
    path('schedule/', schedule, name='schedule'),
    path('lessons/new/', lesson_create, name='lesson_create'),
    path('lessons/<int:pk>/edit/', lesson_update, name='lesson_update'),
    path(
        'lessons/<int:pk>/payment/',
        lesson_payment_toggle,
        name='lesson_payment'
    ),
]

pydep/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<header>
     <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand" href={% url "lesson:index" %}><span class="fw-bolder text-primary">PyDep</span></a>
{#                <a class="navbar-brand" href={% url "lesson:index" %}><img src="{% static "img/logo/logo.png" %}" width="130" height="70"></a>#}
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                        {% if user.is_staff %}
                            <li class="nav-item"><a class="nav-link {% if view_name  == 'studio:main' %}active{% endif %}" href={% url "studio:main" %}>Редактор курсов</a></li>
                        {% endif %}
                            <li class="nav-item"><a class="nav-link {% if view_name  == 'lesson:courses' %}active{% endif %}" href={% url "lesson:courses" %}>Курсы</a></li>
                        <li class="nav-item"><a class="nav-link {% if view_name  == 'tutor:projectbox' %}active{% endif %}" href={% url "tutor:my_tutor" %}>Мой репетитор</a></li>
                            {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link {% if view_name  == 'lesson:profile' %}active{% endif %}" href={% url "lesson:profile" %}>Профиль</a></li>


                            {% else %}
                                <li class="nav-item"><a class="nav-link {% if view_name  == 'users:signin' %}active{% endif %}" href={% url "users:signin" %}>Вход</a></li>
                                <li class="nav-item"><a class="nav-link {% if view_name  == 'users:signup' %}active{% endif %}" href={% url "users:signup" %}>Регистрация</a></li>
                            {% endif %}

                        </ul>
                    </div>
                </div>
            </nav>
</header>
{% endwith %}